export const TRADEMARK_ITEM = 'TRADEMARK_ITEM';
export const INDUSTRIAL_DESIGNS_ITEM = 'INDUSTRIAL_DESIGNS_ITEM';
export const SUBMITTED_REQUEST_ITEM = 'SUBMITTED_REQUEST_ITEM';
export const SUBMITTED_REQUEST_PATENT_ITEM = 'SUBMITTED_REQUEST_PATENT_ITEM';
export const CHECK_RESULT_ITEM = 'CHECK_RESULT_ITEM';
